version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ng_gleam
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  web:
    build: ./
    container_name: dg_gleam
    command: >
      bash -c "pip install gunicorn
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn mwasurvey.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000"
    volumes:
      - ./:/code
      - ./static:/static
