# Generated by Django 2.1.2 on 2018-11-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('input_info', models.TextField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('checkbox', 'Checkbox'), ('range', 'Range (Min, Max)'), ('select', 'Select'), ('datetime', 'Date Time')], default='text', max_length=50)),
                ('initial_value', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchInputGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.SmallIntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchInputOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('search_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchInput')),
            ],
        ),
        migrations.AddField(
            model_name='searchinput',
            name='search_input_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchInputGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='searchinputoption',
            unique_together={('search_input', 'name'), ('search_input', 'display_order')},
        ),
        migrations.AlterUniqueTogether(
            name='searchinput',
            unique_together={('search_input_group', 'name'), ('search_input_group', 'display_order')},
        ),
    ]
