# Generated by Django 2.1.2 on 2018-12-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('input_info', models.TextField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('Integer', 'Integer'), ('Text', 'Text'), ('Float', 'Float'), ('Bool', 'Bool'), ('Text(Time)', 'Text(Time)')], default='Text', max_length=50)),
                ('input_type', models.CharField(choices=[('Text', 'Text'), ('number', 'Number (Int)'), ('min_number', 'Min Number (Int)'), ('max_number', 'Max Number (Int)'), ('max_absolute_number', 'Max Absolute Number (Int)'), ('checkbox', 'Checkbox'), ('radius', 'RADIUS (Point, +/-)'), ('range', 'Range (Min, Max)'), ('select', 'Select'), ('datetime', 'Date Time'), ('datetime_range', 'Date Range (Start, End)')], default='Text', max_length=50)),
                ('initial_value', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchInputGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.SmallIntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchInputOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('search_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchInput')),
            ],
        ),
        migrations.CreateModel(
            name='SearchPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('display_order', models.SmallIntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchPageDisplayColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('search_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchPage')),
            ],
        ),
        migrations.CreateModel(
            name='SearchPageInputGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('search_input_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchInputGroup')),
                ('search_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchPage')),
            ],
        ),
        migrations.AddField(
            model_name='searchinput',
            name='search_input_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchInputGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='searchpageinputgroup',
            unique_together={('search_page', 'search_input_group')},
        ),
        migrations.AlterUniqueTogether(
            name='searchpagedisplaycolumn',
            unique_together={('search_page', 'table_name', 'field_name'), ('search_page', 'display_order')},
        ),
        migrations.AlterUniqueTogether(
            name='searchinputoption',
            unique_together={('search_input', 'display_order'), ('search_input', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='searchinput',
            unique_together={('search_input_group', 'name'), ('search_input_group', 'display_order')},
        ),
    ]
