# Generated by Django 2.1.2 on 2018-11-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mwasurveyweb', '0005_insert_search_page_input_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPageDisplayColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('search_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.SearchPage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='searchpagedisplaycolumn',
            unique_together={('search_page', 'table_name', 'field_name'), ('search_page', 'display_order')},
        ),
    ]
