# Generated by Django 2.1.2 on 2018-12-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mwasurveyweb', '0006_insert_search_page_display_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SkyPlotsConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_status', models.CharField(max_length=255, unique=True)),
                ('colour', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mwasurveyweb.Colour')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('name', 'code')},
        ),
    ]
