# Generated by Django 2.1.2 on 2018-11-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwasurveyweb', '0006_auto_20181116_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinput',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number (Int)'), ('min_number', 'Min Number (Int)'), ('max_number', 'Max Number (Int)'), ('max_absolute_number', 'Max Absolute Number (Int)'), ('checkbox', 'Checkbox'), ('radius', 'RADIUS (Point, +/-)'), ('range', 'Range (Min, Max)'), ('select', 'Select'), ('datetime', 'Date Time'), ('datetime_range', 'Date Range (Start, End)')], default='text', max_length=50),
        ),
    ]
