# Generated by Django 2.1.2 on 2018-12-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwasurveyweb', '0008_insert_skyplot_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='colour',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
