# Generated by Django 2.2.4 on 2019-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwasurveyweb', '0008_update_search_observation_starttime_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinput',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number (Int)'), ('min_number', 'Min Number (Int)'), ('max_number', 'Max Number (Int)'), ('max_absolute_number', 'Max Absolute Number (Int)'), ('checkbox', 'Checkbox'), ('radius', 'RADIUS (Point, +/-)'), ('range', 'Range (Min, Max)'), ('range_integer', 'Range Integer (Min, Max)'), ('range_non_negative_int', 'Range Non-negative Integer (Min, Max)'), ('select', 'Select'), ('gps_datetime', 'GPS Date Time'), ('gps_datetime_range', 'GPS Date Range (Start, End)'), ('unix_datetime', 'UNIX Date Time'), ('unix_datetime_range', 'UNIX Date Range (Start, End)')], default='Text', max_length=50),
        ),
    ]
